# Generated by Django 5.1.6 on 2025-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('meals', 'Meals'), ('office', 'Office Supplies'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=50),
        ),
    ]
