# Generated by Django 5.1.6 on 2025-04-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_receipt_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='expense_category',
            field=models.CharField(choices=[('travel', 'Travel'), ('meals', 'Meals'), ('office', 'Office Supplies'), ('utilities', 'Utilities'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
