# Generated by Django 5.1.6 on 2025-02-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_submission_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
