# Generated by Django 5.1.6 on 2025-02-15 02:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_submission_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="receipt_name_id",
            field=models.CharField(
                default=app.models.create_default_receipt_name, max_length=200
            ),
        ),
    ]
