# Generated by Django 5.1.6 on 2025-04-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_receipt_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='expense_category',
            field=models.CharField(choices=[('travel', 'Travel'), ('food', 'Food & Drinks'), ('office', 'Office Supplies'), ('utilities', 'Utilities'), ('parking', 'Parking & Tolls'), ('training', 'Training & Workshops'), ('software', 'Software & Subscriptions'), ('equipment', 'Equipment Purchases'), ('maintenance', 'Vehicle Maintenance'), ('shipping', 'Shipping & Delivery'), ('insurance', 'Insurance'), ('marketing', 'Marketing & Advertising'), ('events', 'Conferences & Events'), ('gifts', 'Client Gifts'), ('admin', 'Administrative Fees'), ('recruiting', 'Recruiting Expenses'), ('employee_wellness', 'Employee Wellness & Perks'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
