# Generated by Django 5.1.6 on 2025-02-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_receipt_receipt_name_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="line_items",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
