# Generated by Django 5.1.6 on 2025-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_receipt_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
