# Generated by Django 5.1.6 on 2025-04-17 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_submission_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="receipt_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="When did you get this receipt?",
            ),
        ),
    ]
