# Generated by Django 5.1.6 on 2025-02-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_receipt_line_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="receipt_name_id",
            new_name="receipt_name",
        ),
        migrations.AlterField(
            model_name="receipt",
            name="line_items",
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
