# Generated by Django 5.1.6 on 2025-02-15 05:30

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_rename_receipt_name_id_receipt_receipt_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="receipt_name",
            field=models.CharField(
                default=app.models.create_default_receipt_name, max_length=50
            ),
        ),
    ]
